apiVersion: v1
kind: Pod
metadata:
  name: service-buy
spec:

  restartPolicy: Always

  volumes:
  - name: shared-data
    emptyDir: {}
  - name: log-data
    persistentVolumeClaim:
      claimName: tsf-pvc

  nodeSelector:
    nodename: master

  containers:

  - name: service-buy-ctr
    image: 172.16.0.32:60080/tsf/service-buy
    imagePullPolicy: Always
    env:
      - name: RUN_ARGS
        value: "--server.port=0 --spring.cloud.consul.discovery.heartbeat.ttlValue=60"
    volumeMounts:
    - name: shared-data
      mountPath: /app/servlet/logs
    - name: log-data
      mountPath: /var/log/tsf/demo

  - name: filebeat-ctr
    image: 172.16.0.32:60080/tsf/agent
    imagePullPolicy: Always
    env:
      - name: INSTANCE_ID
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: LOCAL_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
      - name: APP_ID
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: NAMESPACE_ID
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: ES_HOSTS
        value: "'192.168.1.37:9200','192.168.1.38:9200','192.168.1.40:9200'"
    volumeMounts:
    - name: shared-data
      mountPath: /app/servlet/logs

---

apiVersion: v1
kind: Pod
metadata:
  name: service-client
spec:

  restartPolicy: Always

  volumes:
  - name: shared-data
    emptyDir: {}
  - name: log-data
    persistentVolumeClaim:
      claimName: tsf-pvc

  nodeSelector:
    nodename: master

  containers:

  - name: service-client-ctr
    image: 172.16.0.32:60080/tsf/service-client
    imagePullPolicy: Always
    env:
      - name: RUN_ARGS
        value: "--server.port=0 --spring.cloud.consul.discovery.heartbeat.ttlValue=60"
    volumeMounts:
    - name: shared-data
      mountPath: /app/servlet/logs
    - name: log-data
      mountPath: /var/log/tsf/demo

  - name: filebeat-ctr
    image: 172.16.0.32:60080/tsf/agent
    imagePullPolicy: Always
    env:
      - name: INSTANCE_ID
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: LOCAL_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
      - name: APP_ID
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: NAMESPACE_ID
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: ES_HOSTS
        value: "'192.168.1.37:9200','192.168.1.38:9200','192.168.1.40:9200'"
    volumeMounts:
    - name: shared-data
      mountPath: /app/servlet/logs

---

